/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.datafans;


import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
 
/**
 *
 * @author Jacky09
 */
public class Ben extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ben.class.getName());

    /**
     * Creates new form Ben
     */
    public Ben() {
    initComponents();
    cargarTipos();
    cargarMembresias();
    cargarBeneficios();
}
   
   private void cargarTipos() {
    cmbTipo.removeAllItems();
    cmbTipo.addItem("Descuento");
    cmbTipo.addItem("Acceso");
    cmbTipo.addItem("Contenido");
    cmbTipo.addItem("Interacción");
    cmbTipo.addItem("Otro");
    cmbTipo.setSelectedIndex(-1);
}

   private void cargarMembresias() {
    cmbMem.removeAllItems();
    Conexion objetoConexion = new Conexion();
    String sql =
        "SELECT m.ID_membresia, m.NombreMembresia || ' - ' || f.NombreFan || ' (' || m.Estado || ')' AS Info " +
        "FROM Adquisicion.Membresia m " +
        "INNER JOIN Adquisicion.Suscripcion s ON m.ID_suscripcion = s.ID_suscripcion " +
        "INNER JOIN Usuario.Fan f ON s.ID_fan = f.ID_fan " +
        "ORDER BY m.ID_membresia";
 
    try (Connection conn = objetoConexion.establecerConexion();
         Statement st = conn.createStatement();
         ResultSet rs = st.executeQuery(sql)) {
 
        while (rs.next()) {
            cmbMem.addItem(rs.getLong("ID_membresia") + " - " + rs.getString("Info"));
        }
        cmbMem.setSelectedIndex(-1);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al cargar membresías: " + e.toString());
    }
}
   
   private void cargarBeneficios() {
    Conexion objetoConexion = new Conexion();
    DefaultTableModel modelo = new DefaultTableModel();
    modelo.addColumn("ID Beneficio");
    modelo.addColumn("Nombre Beneficio");
    modelo.addColumn("Tipo Beneficio");
 
    jTable1.setModel(modelo);
 
    String sql = "SELECT * FROM Adquisicion.Beneficio ORDER BY ID_beneficio";
 
    try (Connection conn = objetoConexion.establecerConexion();
         Statement st = conn.createStatement();
         ResultSet rs = st.executeQuery(sql)) {
 
        while (rs.next()) {
            Object[] datos = new Object[3];
            datos[0] = rs.getLong("ID_beneficio");
            datos[1] = rs.getString("NombreBeneficio");
            datos[2] = rs.getString("TipoBeneficio");
            modelo.addRow(datos);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al cargar beneficios: " + e.toString());
    }
}
   
   private void limpiarCampos() {
    txtNombreBen.setText("");
    cmbTipo.setSelectedIndex(-1);
    cmbMem.setSelectedIndex(-1);
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelArt = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreBen = new javax.swing.JTextField();
        cmbTipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cmbMem = new javax.swing.JComboBox<>();
        btnMod = new javax.swing.JButton();
        btnAlta = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jPanelArt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Beneficio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 18))); // NOI18N
        jPanelArt.setPreferredSize(new java.awt.Dimension(330, 0));
        jPanelArt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelArtMouseClicked(evt);
            }
        });

        jLabel2.setText("Nombre Beneficio");

        jLabel3.setText("Tipo Beneficio");

        jLabel4.setText("Membresía");

        btnMod.setText("Modificación");
        btnMod.addActionListener(this::btnModActionPerformed);

        btnAlta.setText("Alta");
        btnAlta.addActionListener(this::btnAltaActionPerformed);

        btnBaja.setText("Baja");
        btnBaja.addActionListener(this::btnBajaActionPerformed);

        javax.swing.GroupLayout jPanelArtLayout = new javax.swing.GroupLayout(jPanelArt);
        jPanelArt.setLayout(jPanelArtLayout);
        jPanelArtLayout.setHorizontalGroup(
            jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArtLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelArtLayout.createSequentialGroup()
                        .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreBen)
                            .addComponent(cmbTipo, 0, 201, Short.MAX_VALUE)
                            .addComponent(cmbMem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelArtLayout.createSequentialGroup()
                        .addComponent(btnAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMod)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanelArtLayout.setVerticalGroup(
            jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArtLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreBen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbMem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMod)
                    .addComponent(btnAlta)
                    .addComponent(btnBaja))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tabla Beneficio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 18))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelArt, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelArt, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModActionPerformed
    int filaMod = jTable1.getSelectedRow();
    if (filaMod < 0) {
        JOptionPane.showMessageDialog(null, "Seleccione un beneficio de la tabla.");
        return;
    }
 
    String nombreMod = txtNombreBen.getText().trim();
    String tipoMod   = cmbTipo.getSelectedIndex() != -1 ? cmbTipo.getSelectedItem().toString() : "";
 
    if (nombreMod.isEmpty() || tipoMod.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor complete todos los campos:\n\n• Nombre del beneficio\n• Tipo de beneficio");
        return;
    }
 
    long idBenMod = Long.parseLong(jTable1.getValueAt(filaMod, 0).toString());
 
    Conexion objConMod = new Conexion();
 
    // Validar nombre duplicado excluyendo el registro actual
    String sqlValMod = "SELECT COUNT(*) FROM Adquisicion.Beneficio WHERE NombreBeneficio = ? AND ID_beneficio <> ?";
    try (Connection conn = objConMod.establecerConexion();
         PreparedStatement psVal = conn.prepareStatement(sqlValMod)) {
 
        psVal.setString(1, nombreMod);
        psVal.setLong(2, idBenMod);
        ResultSet rs = psVal.executeQuery();
        rs.next();
        if (rs.getInt(1) > 0) {
            JOptionPane.showMessageDialog(null, "Ya existe otro beneficio con ese nombre.");
            return;
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al validar: " + e.toString());
        return;
    }
 
    String sqlMod = "UPDATE Adquisicion.Beneficio SET NombreBeneficio = ?, TipoBeneficio = ? WHERE ID_beneficio = ?";
    try (Connection conn = objConMod.establecerConexion();
         PreparedStatement ps = conn.prepareStatement(sqlMod)) {
 
        ps.setString(1, nombreMod);
        ps.setString(2, tipoMod);
        ps.setLong(3, idBenMod);
        ps.executeUpdate();
 
        JOptionPane.showMessageDialog(null, "Beneficio modificado correctamente.");
        cargarBeneficios();
        limpiarCampos();
 
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al modificar beneficio: " + e.toString());
    }
    }//GEN-LAST:event_btnModActionPerformed

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
    String nombre = txtNombreBen.getText().trim();
    String tipo   = cmbTipo.getSelectedIndex() != -1 ? cmbTipo.getSelectedItem().toString() : "";
 
    if (nombre.isEmpty() || tipo.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor complete todos los campos:\n\n• Nombre del beneficio\n• Tipo de beneficio");
        return;
    }
 
    Conexion objConAlta = new Conexion();
 
    // Validar que no exista el mismo nombre
    String sqlVal = "SELECT COUNT(*) FROM Adquisicion.Beneficio WHERE NombreBeneficio = ?";
    try (Connection conn = objConAlta.establecerConexion();
         PreparedStatement psVal = conn.prepareStatement(sqlVal)) {
 
        psVal.setString(1, nombre);
        ResultSet rs = psVal.executeQuery();
        rs.next();
        if (rs.getInt(1) > 0) {
            JOptionPane.showMessageDialog(null, "Ya existe un beneficio registrado con ese nombre.");
            return;
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al validar: " + e.toString());
        return;
    }
 
    // Insertar beneficio
    String sqlIns = "INSERT INTO Adquisicion.Beneficio (NombreBeneficio, TipoBeneficio) VALUES (?, ?)";
    try (Connection conn = objConAlta.establecerConexion();
         PreparedStatement ps = conn.prepareStatement(sqlIns)) {
 
        ps.setString(1, nombre);
        ps.setString(2, tipo);
        ps.executeUpdate();
 
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al registrar beneficio: " + e.toString());
        return;
    }
 
    // Si se seleccionó una membresía, vincularla en MembresiaBeneficio
    if (cmbMem.getSelectedIndex() != -1) {
        String selMem = cmbMem.getSelectedItem().toString();
        long idMem = Long.parseLong(selMem.split(" - ")[0].trim());
 
        // Obtener el ID del beneficio recién insertado
        String sqlGetId = "SELECT ID_beneficio FROM Adquisicion.Beneficio WHERE NombreBeneficio = ? ORDER BY ID_beneficio DESC LIMIT 1";
        try (Connection conn = objConAlta.establecerConexion();
             PreparedStatement psId = conn.prepareStatement(sqlGetId)) {
 
            psId.setString(1, nombre);
            ResultSet rs = psId.executeQuery();
            if (rs.next()) {
                long idBen = rs.getLong("ID_beneficio");
                String sqlLink = "INSERT INTO Adquisicion.MembresiaBeneficio (ID_membresia, ID_beneficio) VALUES (?, ?)";
                try (PreparedStatement psLink = conn.prepareStatement(sqlLink)) {
                    psLink.setLong(1, idMem);
                    psLink.setLong(2, idBen);
                    psLink.executeUpdate();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Beneficio registrado, pero no se pudo vincular a la membresía: " + e.toString());
        }
    }
 
    cargarBeneficios();
    limpiarCampos();
    }//GEN-LAST:event_btnAltaActionPerformed

    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed
    int filaBaja = jTable1.getSelectedRow();
    if (filaBaja < 0) {
        JOptionPane.showMessageDialog(null, "Seleccione un beneficio de la tabla.");
        return;
    }
 
    long idBen = Long.parseLong(jTable1.getValueAt(filaBaja, 0).toString());
 
    int confirm = JOptionPane.showConfirmDialog(null,
        "¿Está seguro de eliminar este beneficio?\nTambién se eliminará su vínculo con membresías.",
        "Confirmar eliminación", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
 
    if (confirm != JOptionPane.YES_OPTION) return;
 
    Conexion objConBaja = new Conexion();
    try (Connection conn = objConBaja.establecerConexion()) {
        conn.setAutoCommit(false);
 
        // Primero eliminar vínculos en MembresiaBeneficio
        PreparedStatement psDel1 = conn.prepareStatement(
            "DELETE FROM Adquisicion.MembresiaBeneficio WHERE ID_beneficio = ?");
        psDel1.setLong(1, idBen);
        psDel1.executeUpdate();
 
        // Luego eliminar el beneficio
        PreparedStatement psDel2 = conn.prepareStatement(
            "DELETE FROM Adquisicion.Beneficio WHERE ID_beneficio = ?");
        psDel2.setLong(1, idBen);
        psDel2.executeUpdate();
 
        conn.commit();
        JOptionPane.showMessageDialog(null, "Beneficio eliminado correctamente.");
        cargarBeneficios();
        limpiarCampos();
 
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al eliminar beneficio: " + e.toString());
    }
    }//GEN-LAST:event_btnBajaActionPerformed

    private void jPanelArtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelArtMouseClicked

    }//GEN-LAST:event_jPanelArtMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int fila = jTable1.getSelectedRow();
        if (fila >= 0) {
        txtNombreBen.setText(jTable1.getValueAt(fila, 1).toString());
        cmbTipo.setSelectedItem(jTable1.getValueAt(fila, 2).toString());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ben().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnMod;
    private javax.swing.JComboBox<String> cmbMem;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelArt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtNombreBen;
    // End of variables declaration//GEN-END:variables
}
