/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.datafans;


import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
 
/**
 *
 * @author Jacky09
 */
public class Ben extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ben.class.getName());

    /**
     * Creates new form Ben
     */
    public Ben() {
    initComponents();
    // Rellenar las opciones del JComboBox fijas
    cargarTipos();
    // Cargar los registros existentes desde la Base de Datos
    cargarBeneficios();
    aplicarPermisosPorRol();
    }

    private void aplicarPermisosPorRol() {
        String rol = Conexion.rolActual;
        
        if (rol.equals("Editor")) {
            // El editor puede dar de Alta y Modificar, pero NO puede dar de Baja (Delete)
            btnBaja.setEnabled(false);
        } else if (rol.equals("Lector")) {
            // El lector SOLO puede consultar. No puede dar de Alta, Baja ni Modificar
            btnAlta.setEnabled(false);
            btnBaja.setEnabled(false);
            btnMod.setEnabled(false);
        }
        // Si es "Admin", no entra a ninguna condición y conserva todos los botones activos.
    }
   
   private void cargarTipos() {
    cmbTipo.removeAllItems();
    cmbTipo.addItem("Descuentos");
    cmbTipo.addItem("Promociones");
    cmbTipo.addItem("Mercancía exclusiva");
    cmbTipo.addItem("Acceso anticipado");
    cmbTipo.addItem("Meet & Greet");
    cmbTipo.setSelectedIndex(-1);
}

   private void cargarBeneficios() {
    Conexion objetoConexion = new Conexion();
    DefaultTableModel modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Evita la edición directa en las celdas
        }
    };
    
    modelo.addColumn("ID");
    modelo.addColumn("Nombre Beneficio");
    modelo.addColumn("Tipo Beneficio");
    
    jTable1.setModel(modelo);
    
    // Ocultar columna técnica ID de la vista del usuario
    jTable1.getColumnModel().getColumn(0).setMinWidth(0);
    jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
    jTable1.getColumnModel().getColumn(0).setPreferredWidth(0);
    
    String sql = "SELECT ID_beneficio, NombreBeneficio, TipoBeneficio "
               + "FROM Adquisicion.Beneficio "
               + "ORDER BY ID_beneficio;";
               
    try (Connection conn = objetoConexion.establecerConexion();
         Statement st = conn.createStatement();
         ResultSet rs = st.executeQuery(sql)) {
         
        while (rs.next()) {
            Object[] fila = new Object[3];
            fila[0] = rs.getLong("ID_beneficio");
            fila[1] = rs.getString("NombreBeneficio");
            fila[2] = rs.getString("TipoBeneficio");
            modelo.addRow(fila);
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al cargar beneficios: " + e.toString(),
                "Error", JOptionPane.ERROR_MESSAGE);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelArt = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreBen = new javax.swing.JTextField();
        cmbTipo = new javax.swing.JComboBox<>();
        btnMod = new javax.swing.JButton();
        btnAlta = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setTitle("Beneficio");

        jPanelArt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanelArt.setPreferredSize(new java.awt.Dimension(330, 0));
        jPanelArt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelArtMouseClicked(evt);
            }
        });

        jLabel2.setText("Nombre Beneficio");

        jLabel3.setText("Tipo Beneficio");

        cmbTipo.addActionListener(this::cmbTipoActionPerformed);

        btnMod.setText("Modificación");
        btnMod.addActionListener(this::btnModActionPerformed);

        btnAlta.setText("Alta");
        btnAlta.addActionListener(this::btnAltaActionPerformed);

        btnBaja.setText("Baja");
        btnBaja.addActionListener(this::btnBajaActionPerformed);

        javax.swing.GroupLayout jPanelArtLayout = new javax.swing.GroupLayout(jPanelArt);
        jPanelArt.setLayout(jPanelArtLayout);
        jPanelArtLayout.setHorizontalGroup(
            jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArtLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelArtLayout.createSequentialGroup()
                        .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbTipo, 0, 201, Short.MAX_VALUE)
                            .addComponent(txtNombreBen)))
                    .addGroup(jPanelArtLayout.createSequentialGroup()
                        .addComponent(btnAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMod)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanelArtLayout.setVerticalGroup(
            jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArtLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreBen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMod)
                    .addComponent(btnAlta)
                    .addComponent(btnBaja))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Beneficio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 18))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelArt, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanelArt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModActionPerformed
    int fila = jTable1.getSelectedRow();
    if (fila < 0) {
        JOptionPane.showMessageDialog(null, "Seleccione un beneficio de la tabla para modificar.",
                "Ninguna Selección", JOptionPane.INFORMATION_MESSAGE);
        return;
    }
    
    String nombre = txtNombreBen.getText().trim();
    String tipo = (cmbTipo.getSelectedItem() != null) ? cmbTipo.getSelectedItem().toString() : "";
    
    if (nombre.isEmpty() || tipo.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Complete todos los campos (Nombre y Tipo de beneficio).",
                "Campos Incompletos", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    long idBeneficio = Long.parseLong(jTable1.getValueAt(fila, 0).toString());
    
    Conexion objetoConexion = new Conexion();
    try (Connection conn = objetoConexion.establecerConexion()) {
        conn.setAutoCommit(false);
        
        try {
            // Validar si existe otro registro idéntico con ID distinto
            String sqlVal = "SELECT COUNT(*) FROM Adquisicion.Beneficio WHERE NombreBeneficio = ? AND TipoBeneficio = ? AND ID_beneficio <> ?;";
            PreparedStatement psVal = conn.prepareStatement(sqlVal);
            psVal.setString(1, nombre);
            psVal.setString(2, tipo);
            psVal.setLong(3, idBeneficio);
            ResultSet rs = psVal.executeQuery();
            
            if (rs.next() && rs.getInt(1) > 0) {
                JOptionPane.showMessageDialog(null, "Ya existe otro beneficio con ese mismo nombre y tipo.",
                        "Conflicto de Datos", JOptionPane.WARNING_MESSAGE);
                conn.rollback();
                return;
            }
            
            // Actualizar
            String sqlUpdate = "UPDATE Adquisicion.Beneficio SET NombreBeneficio = ?, TipoBeneficio = ? WHERE ID_beneficio = ?;";
            PreparedStatement psUpdate = conn.prepareStatement(sqlUpdate);
            psUpdate.setString(1, nombre);
            psUpdate.setString(2, tipo);
            psUpdate.setLong(3, idBeneficio);
            
            psUpdate.executeUpdate();
            conn.commit();
            
            JOptionPane.showMessageDialog(null, "Beneficio modificado exitosamente.");
            cargarBeneficios();
            limpiarCampos();
            
        } catch (Exception ex) {
            conn.rollback();
            throw ex;
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al modificar beneficio: " + e.toString(),
                "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnModActionPerformed

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
    String nombre = txtNombreBen.getText().trim();
    String tipo = (cmbTipo.getSelectedItem() != null) ? cmbTipo.getSelectedItem().toString() : "";
    
    if (nombre.isEmpty() || tipo.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Complete todos los campos (Nombre y Tipo de beneficio).",
                "Campos Vacíos", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    Conexion objetoConexion = new Conexion();
    try (Connection conn = objetoConexion.establecerConexion()) {
        conn.setAutoCommit(false); // Manejo controlado de transacciones
        
        try {
            // Validar Duplicidad
            String sqlVal = "SELECT COUNT(*) FROM Adquisicion.Beneficio WHERE NombreBeneficio = ? AND TipoBeneficio = ?;";
            PreparedStatement psVal = conn.prepareStatement(sqlVal);
            psVal.setString(1, nombre);
            psVal.setString(2, tipo);
            ResultSet rs = psVal.executeQuery();
            
            if (rs.next() && rs.getInt(1) > 0) {
                JOptionPane.showMessageDialog(null, "Ya existe un beneficio registrado con ese mismo nombre y tipo.",
                        "Registro Duplicado", JOptionPane.WARNING_MESSAGE);
                conn.rollback();
                return;
            }
            
            // Insertar
            String sqlInsert = "INSERT INTO Adquisicion.Beneficio (NombreBeneficio, TipoBeneficio) VALUES (?, ?);";
            PreparedStatement psInsert = conn.prepareStatement(sqlInsert);
            psInsert.setString(1, nombre);
            psInsert.setString(2, tipo);
            
            psInsert.executeUpdate();
            conn.commit();
            
            JOptionPane.showMessageDialog(null, "Beneficio creado exitosamente.");
            cargarBeneficios();
            limpiarCampos();
            
        } catch (Exception ex) {
            conn.rollback();
            throw ex;
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al crear beneficio: " + e.toString(),
                "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnAltaActionPerformed

    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed
    int fila = jTable1.getSelectedRow();
    if (fila < 0) {
        JOptionPane.showMessageDialog(null, "Seleccione un beneficio para eliminar.",
                "Ninguna Selección", JOptionPane.INFORMATION_MESSAGE);
        return;
    }
    
    int respuesta = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar este beneficio?\nSe removerán sus relaciones asociadas.",
            "Confirmar eliminación", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            
    if (respuesta != JOptionPane.YES_OPTION) return;
    
    long idBeneficio = Long.parseLong(jTable1.getValueAt(fila, 0).toString());
    
    Conexion objetoConexion = new Conexion();
    try (Connection conn = objetoConexion.establecerConexion()) {
        conn.setAutoCommit(false);
        
        try {
            // 1. Eliminar de la tabla relacional intermedia
            String sqlDeleteRel = "DELETE FROM Adquisicion.MembresiaBeneficio WHERE ID_beneficio = ?;";
            try (PreparedStatement psRel = conn.prepareStatement(sqlDeleteRel)) {
                psRel.setLong(1, idBeneficio);
                psRel.executeUpdate();
            }
            
            // 2. Eliminar de la tabla base Beneficio
            String sqlDeleteBen = "DELETE FROM Adquisicion.Beneficio WHERE ID_beneficio = ?;";
            try (PreparedStatement psBen = conn.prepareStatement(sqlDeleteBen)) {
                psBen.setLong(1, idBeneficio);
                psBen.executeUpdate();
            }
            
            conn.commit();
            JOptionPane.showMessageDialog(null, "Beneficio eliminado exitosamente.");
            cargarBeneficios();
            limpiarCampos();
            
        } catch (Exception ex) {
            conn.rollback();
            throw ex;
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al eliminar beneficio: " + e.toString(),
                "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnBajaActionPerformed

    private void jPanelArtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelArtMouseClicked

    }//GEN-LAST:event_jPanelArtMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int fila = jTable1.getSelectedRow();
    if (fila >= 0) {
        txtNombreBen.setText(jTable1.getValueAt(fila, 1).toString());
        
        String tipo = jTable1.getValueAt(fila, 2).toString();
        // Sincronizar el JComboBox según el texto plano de la celda
        cmbTipo.setSelectedItem(tipo);
    }
    }//GEN-LAST:event_jTable1MouseClicked

    private void limpiarCampos() {
    txtNombreBen.setText("");
    cmbTipo.setSelectedIndex(-1);
    jTable1.clearSelection();
    }
    
    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Ben().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnMod;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelArt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtNombreBen;
    // End of variables declaration//GEN-END:variables
}
