/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.datafans;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jacky09
 */
public class Cont extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Cont.class.getName());

    /**
     * Creates new form Cont
     */
    public Cont() {
        initComponents();
        buttonGroup1.add(btnSi);
        buttonGroup1.add(btnNo);
        btnNo.setSelected(true); // Selección por defecto (Equivalente al rbNo.Checked = true de C#)

        // Carga de datos inicial
        cargarArtistas();
        cargarTiposContenido();
        cargarContenido();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanelArt = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        btnMod = new javax.swing.JButton();
        btnAlta = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();
        cmbTipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        cmbArtista = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btnSi = new javax.swing.JRadioButton();
        btnNo = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCont = new javax.swing.JTable();

        setTitle("Contenido");

        jPanelArt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contenido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 18))); // NOI18N
        jPanelArt.setPreferredSize(new java.awt.Dimension(330, 0));

        jLabel2.setText("Título");

        jLabel3.setText("Tipo Contenido");

        btnMod.setText("Modificación");
        btnMod.addActionListener(this::btnModActionPerformed);

        btnAlta.setText("Alta");
        btnAlta.addActionListener(this::btnAltaActionPerformed);

        btnBaja.setText("Baja");
        btnBaja.addActionListener(this::btnBajaActionPerformed);

        jLabel4.setText("Exclusivo");

        jLabel5.setText("Artista");

        btnSi.setText("Si");
        btnSi.setActionCommand("btnSi");
        btnSi.addActionListener(this::btnSiActionPerformed);

        btnNo.setText("No");
        btnNo.setActionCommand("btnNo");
        btnNo.addActionListener(this::btnNoActionPerformed);

        javax.swing.GroupLayout jPanelArtLayout = new javax.swing.GroupLayout(jPanelArt);
        jPanelArt.setLayout(jPanelArtLayout);
        jPanelArtLayout.setHorizontalGroup(
            jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArtLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelArtLayout.createSequentialGroup()
                        .addComponent(btnAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMod))
                    .addGroup(jPanelArtLayout.createSequentialGroup()
                        .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelArtLayout.createSequentialGroup()
                                .addComponent(btnNo)
                                .addGap(18, 18, 18)
                                .addComponent(btnSi))
                            .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                .addComponent(cmbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbArtista, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelArtLayout.setVerticalGroup(
            jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArtLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbArtista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSi)
                    .addComponent(btnNo))
                .addGap(7, 7, 7)
                .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMod)
                    .addComponent(btnAlta)
                    .addComponent(btnBaja))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Contenido ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 18))); // NOI18N

        tbCont.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbCont.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbContMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbCont);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelArt, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelArt, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarTiposContenido() {
    cmbTipo.removeAllItems();
    String[] tipos = {"Video", "Live", "Saludo", "Clip", "Juego", "Behind the Scenes"};
    for (String t : tipos) {
        cmbTipo.addItem(t);
    }
    cmbTipo.setSelectedIndex(-1); // Inicializar sin selección
    }
    
    private void cargarArtistas() {
    Conexion objetoConexion = new Conexion();
    cmbArtista.removeAllItems();
    
    String sql = "SELECT ID_artista, Nombre_Artista FROM Usuario.Artista;";
    
    try (Connection conn = objetoConexion.establecerConexion();
         Statement st = conn.createStatement();
         ResultSet rs = st.executeQuery(sql)) {
        
        while (rs.next()) {
            cmbArtista.addItem(new ComboItem(rs.getLong("ID_artista"), rs.getString("Nombre_Artista")));
        }
        cmbArtista.setSelectedIndex(-1);
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al cargar artistas: " + e.toString(),
                "Error de Carga", JOptionPane.ERROR_MESSAGE);
    }
    }
    
    private void cargarContenido() {
    Conexion objetoConexion = new Conexion();
    DefaultTableModel modelo = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) { return false; }
    };
    
    modelo.addColumn("ID Contenido");
    modelo.addColumn("Título");
    modelo.addColumn("Tipo Contenido");
    modelo.addColumn("Exclusivo");
    modelo.addColumn("ID_artista_oculto");
    modelo.addColumn("Artista");
    
    tbCont.setModel(modelo);
    
    // Ocultar columna técnica del ID de Artista
    tbCont.getColumnModel().getColumn(4).setMinWidth(0);
    tbCont.getColumnModel().getColumn(4).setMaxWidth(0);
    tbCont.getColumnModel().getColumn(4).setPreferredWidth(0);
    
    String sql = "SELECT c.ID_contenido, c.Titulo, c.TipoContenido, c.Exclusivo, c.ID_artista, a.Nombre_Artista "
               + "FROM Adquisicion.Contenido c "
               + "INNER JOIN Usuario.Artista a ON c.ID_artista = a.ID_artista;";
               
    try (Connection conn = objetoConexion.establecerConexion();
         Statement st = conn.createStatement();
         ResultSet rs = st.executeQuery(sql)) {
        
        while (rs.next()) {
            Object[] datos = new Object[6];
            datos[0] = rs.getLong("ID_contenido");
            datos[1] = rs.getString("Titulo");
            datos[2] = rs.getString("TipoContenido");
            datos[3] = rs.getString("Exclusivo");
            datos[4] = rs.getLong("ID_artista");
            datos[5] = rs.getString("Nombre_Artista");
            modelo.addRow(datos);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al cargar contenidos: " + e.toString(),
                "Error de Consulta", JOptionPane.ERROR_MESSAGE);
    }
    }
    
    
    
    private void btnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModActionPerformed
        // TODO add your handling code here:
    int fila = tbCont.getSelectedRow();
    if (fila < 0) {
        JOptionPane.showMessageDialog(null, "Seleccione un contenido de la lista.", 
                "Ninguna Selección", JOptionPane.INFORMATION_MESSAGE);
        return;
    }
    
    String titulo = txtTitulo.getText().trim();
    String tipo = (cmbTipo.getSelectedItem() != null) ? cmbTipo.getSelectedItem().toString() : "";
    String exclusivo = btnSi.isSelected() ? "Si" : "No";
    
    if (titulo.isEmpty() || tipo.isEmpty() || cmbArtista.getSelectedIndex() == -1) {
        JOptionPane.showMessageDialog(null, "Complete todos los campos.", 
                "Campos Incompletos", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    long idContenido = Long.parseLong(tbCont.getValueAt(fila, 0).toString());
    long idArtista = ((ComboItem) cmbArtista.getSelectedItem()).getId();
    
    Conexion objetoConexion = new Conexion();
    try (Connection conn = objetoConexion.establecerConexion()) {
        conn.setAutoCommit(false);
        
        try {
            // 🔍 VALIDAR DUPLICADOS CRUZADOS (Considerando la exclusividad en la discriminación)
            String sqlVal = "SELECT COUNT(*) FROM Adquisicion.Contenido "
                          + "WHERE ID_artista = ? AND Titulo = ? AND TipoContenido = ? AND Exclusivo = ? AND ID_contenido <> ?;";
            PreparedStatement psVal = conn.prepareStatement(sqlVal);
            psVal.setLong(1, idArtista);
            psVal.setString(2, titulo);
            psVal.setString(3, tipo);
            psVal.setString(4, exclusivo);
            psVal.setLong(5, idContenido);
            ResultSet rs = psVal.executeQuery();
            
            if (rs.next() && rs.getInt(1) > 0) {
                JOptionPane.showMessageDialog(null, "Ya existe otro registro con el mismo título, tipo y exclusividad para este artista.", 
                        "Conflicto de Duplicados", JOptionPane.WARNING_MESSAGE);
                conn.rollback();
                return;
            }
            
            // 🟢 ACTUALIZAR
            String sqlUpdate = "UPDATE Adquisicion.Contenido SET ID_artista = ?, Titulo = ?, TipoContenido = ?, Exclusivo = ? WHERE ID_contenido = ?;";
            PreparedStatement psUpdate = conn.prepareStatement(sqlUpdate);
            psUpdate.setLong(1, idArtista);
            psUpdate.setString(2, titulo);
            psUpdate.setString(3, tipo);
            psUpdate.setString(4, exclusivo);
            psUpdate.setLong(5, idContenido);
            
            psUpdate.executeUpdate();
            conn.commit();
            
           // JOptionPane.showMessageDialog(null, "Contenido actualizado correctamente.");
            cargarContenido();
            limpiarCampos();
            
        } catch (Exception ex) {
            conn.rollback();
            throw ex;
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al modificar: " + e.toString(), 
                "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnModActionPerformed

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        // TODO add your handling code here:
    String titulo = txtTitulo.getText().trim();
    String tipo = (cmbTipo.getSelectedItem() != null) ? cmbTipo.getSelectedItem().toString() : "";
    
    if (titulo.isEmpty() || tipo.isEmpty() || cmbArtista.getSelectedIndex() == -1) {
        JOptionPane.showMessageDialog(null, "Complete todos los campos obligatorios.", 
                "Campos Incompletos", JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    long idArtista = ((ComboItem) cmbArtista.getSelectedItem()).getId();
    String exclusivo = btnSi.isSelected() ? "Si" : "No";
    
    Conexion objetoConexion = new Conexion();
    try (Connection conn = objetoConexion.establecerConexion()) {
        conn.setAutoCommit(false);
        
        try {
            // 🔍 VALIDAR DUPLICADOS (Ahora incluyendo la exclusividad)
            String sqlVal = "SELECT COUNT(*) FROM Adquisicion.Contenido "
                          + "WHERE Titulo = ? AND TipoContenido = ? AND ID_artista = ? AND Exclusivo = ?;";
            PreparedStatement psVal = conn.prepareStatement(sqlVal);
            psVal.setString(1, titulo);
            psVal.setString(2, tipo);
            psVal.setLong(3, idArtista);
            psVal.setString(4, exclusivo);
            ResultSet rs = psVal.executeQuery();
            
            if (rs.next() && rs.getInt(1) > 0) {
                JOptionPane.showMessageDialog(null, "Este contenido ya se encuentra registrado con el mismo estado de exclusividad para este artista.", 
                        "Contenido Duplicado", JOptionPane.WARNING_MESSAGE);
                conn.rollback();
                return;
            }
            
            // 🟢 INSERTAR
            String sqlInsert = "INSERT INTO Adquisicion.Contenido (ID_artista, Titulo, TipoContenido, Exclusivo) VALUES (?, ?, ?, ?);";
            PreparedStatement psInsert = conn.prepareStatement(sqlInsert);
            psInsert.setLong(1, idArtista);
            psInsert.setString(2, titulo);
            psInsert.setString(3, tipo);
            psInsert.setString(4, exclusivo);
            
            psInsert.executeUpdate();
            conn.commit();
            
            //JOptionPane.showMessageDialog(null, "Contenido guardado con éxito.");
            cargarContenido();
            limpiarCampos();
            
        } catch (Exception ex) {
            conn.rollback();
            throw ex;
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al guardar el contenido: " + e.toString(), 
                "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnAltaActionPerformed

    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed
        // TODO add your handling code here:
    int fila = tbCont.getSelectedRow();
    if (fila < 0) return;
    
    long idContenido = Long.parseLong(tbCont.getValueAt(fila, 0).toString());
    int confirm = JOptionPane.showConfirmDialog(null, "¿Desea eliminar de forma permanente esta publicación?", 
            "Confirmar Baja", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            
    if (confirm == JOptionPane.YES_OPTION) {
        Conexion objetoConexion = new Conexion();
        String sql = "DELETE FROM Adquisicion.Contenido WHERE ID_contenido = ?;";
        
        try (Connection conn = objetoConexion.establecerConexion();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setLong(1, idContenido);
            ps.executeUpdate();
            
            //JOptionPane.showMessageDialog(null, "Publicación eliminada correctamente.");
            cargarContenido();
            limpiarCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudo borrar el contenido.\nDetalle: " + e.toString(), 
                    "Error al Eliminar", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btnBajaActionPerformed

    private void limpiarCampos() {
    txtTitulo.setText("");
    cmbTipo.setSelectedIndex(-1);
    cmbArtista.setSelectedIndex(-1);
    buttonGroup1.clearSelection(); 
    btnNo.setSelected(true); // Regresar al valor por defecto
    tbCont.clearSelection();
    }
    private void btnSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSiActionPerformed

    private void btnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNoActionPerformed

    private void tbContMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbContMouseClicked
        // TODO add your handling code here:
    int fila = tbCont.getSelectedRow();
    if (fila >= 0) {
        txtTitulo.setText(tbCont.getValueAt(fila, 1).toString());
        
        // Sincronizar Combo Tipo
        String tipo = tbCont.getValueAt(fila, 2).toString();
        cmbTipo.setSelectedItem(tipo);
        
        // Sincronizar RadioButtons
        boolean ex = tbCont.getValueAt(fila, 3).toString().equalsIgnoreCase("Si");
        btnSi.setSelected(ex);
        btnNo.setSelected(!ex);
        
        // Sincronizar Combo Artista mediante ID Oculto
        long idArtTarget = Long.parseLong(tbCont.getModel().getValueAt(fila, 4).toString());
        for (int i = 0; i < cmbArtista.getItemCount(); i++) {
            Object item = cmbArtista.getItemAt(i);
            if (item instanceof ComboItem && ((ComboItem) item).getId() == idArtTarget) {
                cmbArtista.setSelectedIndex(i);
                break;
            }
        }
    }
    }//GEN-LAST:event_tbContMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Cont().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnMod;
    private javax.swing.JRadioButton btnNo;
    private javax.swing.JRadioButton btnSi;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<ComboItem> cmbArtista;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelArt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbCont;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
