/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.datafans;

/**
 *
 * @author Jacky09
 */

import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

public class Fan extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Fan.class.getName());

    /**
     * Creates new form Fan
     */
    public Fan() {
        initComponents();
        cargarFans();
        aplicarPermisosPorRol();
    }

    private void aplicarPermisosPorRol() {
        String rol = Conexion.rolActual;
        
        if (rol.equals("Editor")) {
            // El editor puede dar de Alta y Modificar, pero NO puede dar de Baja (Delete)
            btnBaja.setEnabled(false);
        } else if (rol.equals("Lector")) {
            // El lector SOLO puede consultar. No puede dar de Alta, Baja ni Modificar
            btnAlta.setEnabled(false);
            btnBaja.setEnabled(false);
            btnMod.setEnabled(false);
        }
        // Si es "Admin", no entra a ninguna condición y conserva todos los botones activos.
    }
    
    private void cargarFans() {
    Conexion objetoConexion = new Conexion();
    // Definimos el modelo de la tabla
    DefaultTableModel modelo = new DefaultTableModel();
    modelo.addColumn("ID Fan");
    modelo.addColumn("Nombre");
    modelo.addColumn("Teléfono");
    modelo.addColumn("Email");
    modelo.addColumn("Fecha de Registro");
    
    tbFan.setModel(modelo);
    
    // Usamos el esquema Usuario.Fan como en tu script
    String sql = "SELECT * FROM Usuario.Fan;";
    
    try (Connection conn = objetoConexion.establecerConexion();
         Statement st = conn.createStatement();
         ResultSet rs = st.executeQuery(sql)) {
        
        while (rs.next()) {
            Object[] datos = new Object[5];
            datos[0] = rs.getLong("ID_fan");
            datos[1] = rs.getString("NombreFan");
            datos[2] = rs.getString("Telefono");
            datos[3] = rs.getString("Email");
            datos[4] = rs.getDate("Fecha_registro");
            modelo.addRow(datos);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al cargar fans: " + e.toString());
        }
    }   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtNombreFan = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btnAlta = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();
        btnMod = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbFan = new javax.swing.JTable();

        setTitle("Fan");

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.setPreferredSize(new java.awt.Dimension(330, 0));

        jLabel1.setText("Email");

        jLabel2.setText("Nombre Fan");

        jLabel3.setText("Teléfono");

        txtNombreFan.addActionListener(this::txtNombreFanActionPerformed);

        btnAlta.setText("Alta");
        btnAlta.addActionListener(this::btnAltaActionPerformed);

        btnBaja.setText("Baja");
        btnBaja.addActionListener(this::btnBajaActionPerformed);

        btnMod.setText("Modificación");
        btnMod.addActionListener(this::btnModActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(btnBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMod, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(14, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtNombreFan, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreFan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMod)
                    .addComponent(btnAlta)
                    .addComponent(btnBaja))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Fan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 18))); // NOI18N

        tbFan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbFan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbFanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbFan);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
        // TODO add your handling code here:
    String nombre = txtNombreFan.getText();
    String telefono = txtTelefono.getText();
    String email = txtEmail.getText();
    // En Postgres usamos la fecha del sistema mediante SQL o java.sql.Date
    java.sql.Date fechaRegistro = new java.sql.Date(System.currentTimeMillis());

    if (nombre.isEmpty() || telefono.isEmpty() || email.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Por favor complete todos los campos.");
        return;
    }

    Conexion objetoConexion = new Conexion();
    try (Connection conn = objetoConexion.establecerConexion()) {
        // Validación de duplicados
        String valSql = "SELECT Telefono, Email FROM Usuario.Fan WHERE Telefono = ? OR Email = ?;";
        try (PreparedStatement psVal = conn.prepareStatement(valSql)) {
            psVal.setString(1, telefono);
            psVal.setString(2, email);
            try (ResultSet rs = psVal.executeQuery()) {
                if (rs.next()) {
                    String telBD = rs.getString("Telefono");
                    String emailBD = rs.getString("Email");
                    
                    if (telefono.equals(telBD)) {
                        JOptionPane.showMessageDialog(null, "El número de teléfono ya está registrado con otro fan.", 
                                "Datos Duplicados", JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                    if (email.equalsIgnoreCase(emailBD)) {
                        JOptionPane.showMessageDialog(null, "El email ya está registrado con otro fan.", 
                                "Datos Duplicados", JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                }
            }
        }

        // Inserción
        String sql = "INSERT INTO Usuario.Fan (NombreFan, Telefono, Email, Fecha_registro) VALUES (?, ?, ?, ?);";
        PreparedStatement ps = conn.prepareStatement(sql);
        ps.setString(1, nombre);
        ps.setString(2, telefono);
        ps.setString(3, email);
        ps.setDate(4, fechaRegistro);
        
        ps.executeUpdate();
        //JOptionPane.showMessageDialog(null, "Registro exitoso");
        cargarFans();
        limpiarCampos();
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.toString());
    }
    }//GEN-LAST:event_btnAltaActionPerformed

    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed
        // TODO add your handling code here:
    int fila = tbFan.getSelectedRow();
    if (fila < 0) {
        JOptionPane.showMessageDialog(null, "Seleccione un fan de la lista.");
        return;
    }

    long idFan = Long.parseLong(tbFan.getValueAt(fila, 0).toString());
    int confirm = JOptionPane.YES_OPTION;
            //showConfirmDialog(null, "¿Está seguro? Se borrarán registros asociados.", "Confirmar", JOptionPane.YES_NO_OPTION);
    
    if (confirm == JOptionPane.YES_OPTION) {
        Conexion objetoConexion = new Conexion();
        String sql = "DELETE FROM Usuario.Fan WHERE ID_fan = ?;";
        try (Connection conn = objetoConexion.establecerConexion();
             PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setLong(1, idFan);
            ps.executeUpdate();
            cargarFans();
            limpiarCampos();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al eliminar: " + e.toString());
        }
    }
    }//GEN-LAST:event_btnBajaActionPerformed

    private void btnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModActionPerformed
        // TODO add your handling code here:
    int fila = tbFan.getSelectedRow();
    if (fila < 0) {
        JOptionPane.showMessageDialog(null, "Seleccione un fan para modificar.");
        return;
    }

    long idFan = Long.parseLong(tbFan.getValueAt(fila, 0).toString());
    String nombre = txtNombreFan.getText().trim();
    String telefono = txtTelefono.getText().trim();
    String email = txtEmail.getText().trim();
    Conexion objetoConexion = new Conexion();
    try (Connection conn = objetoConexion.establecerConexion()) {
        
        // 1. VALIDAR DUPLICADOS EXCLUYENDO EL ID ACTUAL (<> ?)
        String valSql = "SELECT Telefono, Email FROM Usuario.Fan WHERE (Telefono = ? OR Email = ?) AND ID_fan <> ?;";
        try (PreparedStatement psVal = conn.prepareStatement(valSql)) {
            psVal.setString(1, telefono);
            psVal.setString(2, email);
            psVal.setLong(3, idFan);
            
            try (ResultSet rs = psVal.executeQuery()) {
                if (rs.next()) {
                    String telBD = rs.getString("Telefono");
                    String emailBD = rs.getString("Email");
                    
                    if (telefono.equals(telBD)) {
                        JOptionPane.showMessageDialog(null, "No se puede actualizar: El teléfono ya le pertenece a otro fan.", 
                                "Datos Duplicados", JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                    if (email.equalsIgnoreCase(emailBD)) {
                        JOptionPane.showMessageDialog(null, "No se puede actualizar: El Email ya le pertenece a otro fan.", 
                                "Datos Duplicados", JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                }
            }
        }

        // 2. SI PASA LA VALIDACIÓN, PROCEDE CON EL UPDATE
        String sql = "UPDATE Usuario.Fan SET NombreFan = ?, Telefono = ?, Email = ? WHERE ID_fan = ?;";
        try (PreparedStatement ps = conn.prepareStatement(sql)) {
            ps.setString(1, nombre);
            ps.setString(2, telefono);
            ps.setString(3, email);
            ps.setLong(4, idFan);
            
            ps.executeUpdate();
            //JOptionPane.showMessageDialog(null, "Datos del fan actualizados con éxito.");
            cargarFans();
            limpiarCampos();
        }
        
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al modificar: " + e.toString(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnModActionPerformed

    private void txtNombreFanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreFanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreFanActionPerformed

    private void tbFanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbFanMouseClicked

    int fila = tbFan.getSelectedRow();
    if (fila >= 0) {
        txtNombreFan.setText(tbFan.getValueAt(fila, 1).toString());
        txtTelefono.setText(tbFan.getValueAt(fila, 2).toString());
        txtEmail.setText(tbFan.getValueAt(fila, 3).toString());
    }
    }//GEN-LAST:event_tbFanMouseClicked
    private void limpiarCampos() {
    txtNombreFan.setText("");
    txtTelefono.setText("");
    txtEmail.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Fan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnMod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbFan;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombreFan;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
