
package com.mycompany.datafans;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Jacky09
 */
public class Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Menu.class.getName());

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        
        //aplicarPermisosPorRolMenu();
        
    Conexion objetoConexion = new Conexion();
        
    }
        
    
    
    // Si es Admin conserva todas las opciones de los JComboBox intactas.

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMenu = new javax.swing.JPanel();
        cmbUsuarios = new javax.swing.JComboBox<>();
        cmbAdm = new javax.swing.JComboBox<>();
        cmbAdq = new javax.swing.JComboBox<>();
        jLbl = new javax.swing.JLabel();
        jLblAdm = new javax.swing.JLabel();
        jLblAdq = new javax.swing.JLabel();
        cmbRep = new javax.swing.JComboBox<>();
        jLblAdm1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbUsuarios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fan", "Artista" }));
        cmbUsuarios.setSelectedIndex(-1);
        cmbUsuarios.setToolTipText("Fan");
        cmbUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmbUsuariosMouseClicked(evt);
            }
        });
        cmbUsuarios.addActionListener(this::cmbUsuariosActionPerformed);

        cmbAdm.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbAdm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Compra", "Pago" }));
        cmbAdm.setSelectedIndex(-1);
        cmbAdm.addActionListener(this::cmbAdmActionPerformed);

        cmbAdq.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbAdq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Suscripción", "Membresía", "Beneficio", "Membresía Beneficio", "Contenido", "Membresía Contenido", "Producto" }));
        cmbAdq.setSelectedIndex(-1);
        cmbAdq.addActionListener(this::cmbAdqActionPerformed);

        jLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLbl.setText("Usuario");

        jLblAdm.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLblAdm.setText("Administración");

        jLblAdq.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLblAdq.setText("Adquisición");

        cmbRep.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmbRep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Reporte 1", "Reporte 2" }));
        cmbRep.setSelectedIndex(-1);
        cmbRep.addActionListener(this::cmbRepActionPerformed);

        jLblAdm1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLblAdm1.setText("Reportes");

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbRep, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblAdm1)
                    .addGroup(jPanelMenuLayout.createSequentialGroup()
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLbl))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbAdq, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblAdq))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLblAdm))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblAdq))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbAdq, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(jLblAdm1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbRep, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbAdqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAdqActionPerformed
        // TODO add your handling code here:
        String seleccion = cmbAdq.getSelectedItem().toString();
            
        switch (seleccion) {
        case "Suscripción" -> {
            new Sus().setVisible(true);
            
            }

        case "Membresía" -> {
            new Mem().setVisible(true);
            
            }
        case "Beneficio" -> {
            new Ben().setVisible(true);
            
            }
        case "Contenido" -> {
            new Cont().setVisible(true);
            
            }
        case "Membresía Contenido" -> {
            new MemCont().setVisible(true);
            
            }
        case "Membresía Beneficio" -> {
            new MemBen().setVisible(true);
            
            }
        case "Producto" -> {
            new Prod().setVisible(true);
            }

        default -> {
            }
        }
    }//GEN-LAST:event_cmbAdqActionPerformed

    private void cmbUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUsuariosActionPerformed
        String seleccion = cmbUsuarios.getSelectedItem().toString();

        switch (seleccion) {
        case "Fan" -> {
            new Fan().setVisible(true);
            }

        case "Artista" -> {
            new Artista().setVisible(true);
            }

        default -> {
            }
        }
        // opción "Seleccione" u otra
    }//GEN-LAST:event_cmbUsuariosActionPerformed

    private void cmbUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmbUsuariosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbUsuariosMouseClicked

    private void cmbAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAdmActionPerformed
        String seleccion = cmbAdm.getSelectedItem().toString();

        switch (seleccion) {
        case "Compra" -> {
            new Compra().setVisible(true);
            }

        case "Pago" -> {
            String rol = Conexion.rolActual;
            if (rol.equals("Editor")) {
        // Recorremos el combo cmbAdq de atrás hacia adelante para remover de forma segura
        for (int i = cmbAdq.getItemCount() - 1; i >= 0; i--) {
            Object item = cmbAdq.getItemAt(i);
            if (item != null) {
                String textoItem = item.toString().toLowerCase();
                // Si el ítem contiene la palabra clave 'pago', lo eliminamos
                if (textoItem.contains("Pago")) {
                    cmbAdq.removeItemAt(i);
                }
            }
        }
            }
            else 
            new Pago().setVisible(true);
            }

        default -> {
            }
        }
    }//GEN-LAST:event_cmbAdmActionPerformed

    private void cmbRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRepActionPerformed
        // TODO add your handling code here:
        String seleccion = cmbRep.getSelectedItem().toString();

        switch (seleccion) {
        case "Reporte 1" -> {
            new Reporte1().setVisible(true);
            }

        case "Reporte 2" -> {
            new Reporte2().setVisible(true);
            }

        default -> {
            }
        }
    }//GEN-LAST:event_cmbRepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbAdm;
    private javax.swing.JComboBox<String> cmbAdq;
    private javax.swing.JComboBox<String> cmbRep;
    private javax.swing.JComboBox<String> cmbUsuarios;
    private javax.swing.JLabel jLbl;
    private javax.swing.JLabel jLblAdm;
    private javax.swing.JLabel jLblAdm1;
    private javax.swing.JLabel jLblAdq;
    private javax.swing.JPanel jPanelMenu;
    // End of variables declaration//GEN-END:variables
}
