/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.datafans;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Jacky09
 */
public class Pago extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pago.class.getName());

    private Long idMembresia = null;
    /**
     * Creates new form Pago
     */
    public Pago() {
    initComponents();
    cargarBancos();
    limpiarInfoMembresia();
    aplicarPermisosPorRol();
    }

    private void aplicarPermisosPorRol() {
        String rol = Conexion.rolActual;
        
        if (rol.equals("Editor")) {
            // El editor puede dar de Alta y Modificar, pero NO puede dar de Baja (Delete)
            btnBaja.setEnabled(false);
        } else if (rol.equals("Lector")) {
            // El lector SOLO puede consultar. No puede dar de Alta, Baja ni Modificar
            btnAlta.setEnabled(false);
            btnBaja.setEnabled(false);
            btnMod.setEnabled(false);
        }
        // Si es "Admin", no entra a ninguna condición y conserva todos los botones activos.
    }
    public Pago(long idMembresiaNueva) {
        initComponents();
        cargarBancos();
        limpiarInfoMembresia();
        idMembresia = idMembresiaNueva;
        txtIDMem.setText(String.valueOf(idMembresiaNueva));
        cargarInfoMembresia(idMembresiaNueva);
        cargarPagos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private void cargarBancos() {
    cmbBanco.removeAllItems();
    String[] bancos = {"BBVA", "BANAMEX", "BanBajio", "Banorte", "HSBC",
                       "Scotiabank", "Santander", "Inbursa", "IXE", "Interacciones"};
    for (String b : bancos) {
        cmbBanco.addItem(b);
    }
    cmbBanco.setSelectedIndex(-1);
}
    
    private void cargarInfoMembresia(long idMem) {
    Conexion objetoConexion = new Conexion();
    String sql =
        "SELECT m.ID_membresia, m.NombreMembresia, m.Precio, m.Duracion, " +
        "m.Fecha_inicio, m.Fecha_fin, m.Estado, f.NombreFan, a.Nombre_artista " +
        "FROM Adquisicion.Membresia m " +
        "INNER JOIN Adquisicion.Suscripcion s ON m.ID_suscripcion = s.ID_suscripcion " +
        "INNER JOIN Usuario.Fan f ON s.ID_fan = f.ID_fan " +
        "INNER JOIN Usuario.Artista a ON s.ID_artista = a.ID_artista " +
        "WHERE m.ID_membresia = ?";
 
    try (Connection conn = objetoConexion.establecerConexion();
         PreparedStatement ps = conn.prepareStatement(sql)) {
 
        ps.setLong(1, idMem);
        try (ResultSet rs = ps.executeQuery()) {
            if (rs.next()) {
                lblFan.setText(rs.getString("NombreFan") + " - " + rs.getString("Nombre_artista"));
                lblTipo.setText(rs.getString("NombreMembresia") + " ($" + rs.getString("Precio") + ") - " + rs.getString("Duracion"));
 
                java.sql.Date fi = rs.getDate("Fecha_inicio");
                java.sql.Date ff = rs.getDate("Fecha_fin");
                lblInicio.setText(fi != null ? fi.toString() : "No establecida");
                lblFin.setText(ff != null ? ff.toString() : "No establecida");
 
                String estado = rs.getString("Estado");
                lblEdo.setText(estado);
 
                if (estado.equals("Activa")) {
                    lblEdo.setForeground(java.awt.Color.GREEN.darker());
                } else if (estado.equals("Pago Pendiente")) {
                    lblEdo.setForeground(java.awt.Color.ORANGE.darker());
                } else {
                    lblEdo.setForeground(java.awt.Color.RED);
                }
 
                btnAlta.setEnabled(estado.equals("Pago Pendiente"));
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró la membresía con ID: " + idMem);
                limpiarInfoMembresia();
            }
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al cargar membresía: " + e.toString());
        limpiarInfoMembresia();
    }
}
    
   private void limpiarInfoMembresia() {
    lblFan.setText("-");
    lblTipo.setText("-");
    lblInicio.setText("-");
    lblFin.setText("-");
    lblEdo.setText("-");
    lblEdo.setForeground(java.awt.Color.BLACK);
    btnAlta.setEnabled(false);
    idMembresia = null;
}
    
    private void cargarPagos() {
    if (idMembresia == null) {
        tbPago.setModel(new DefaultTableModel());
        return;
    }
 
    Conexion objetoConexion = new Conexion();
    DefaultTableModel modelo = new DefaultTableModel();
    modelo.addColumn("ID Pago");
    modelo.addColumn("Fecha Pago");
    modelo.addColumn("Num. Tarjeta");
    modelo.addColumn("Banco");
    modelo.addColumn("CVV");
    modelo.addColumn("Membresía");
 
    tbPago.setModel(modelo);
 
    String sql =
        "SELECT p.ID_pago, p.Fecha_pago, p.NumTarjeta, p.Banco, p.Cvv, " +
        "m.NombreMembresia || ' - ' || a.Nombre_artista || ' - Suscriptor: ' || f.NombreFan || ' (' || m.Estado || ')' AS MembresiaInfo " +
        "FROM Administrativo.Pago p " +
        "INNER JOIN Adquisicion.Membresia m ON p.ID_membresia = m.ID_membresia " +
        "INNER JOIN Adquisicion.Suscripcion s ON m.ID_suscripcion = s.ID_suscripcion " +
        "INNER JOIN Usuario.Fan f ON s.ID_fan = f.ID_fan " +
        "INNER JOIN Usuario.Artista a ON s.ID_artista = a.ID_artista " +
        "WHERE p.ID_membresia = ? " +
        "ORDER BY p.Fecha_pago DESC";
 
    try (Connection conn = objetoConexion.establecerConexion();
         PreparedStatement ps = conn.prepareStatement(sql)) {
 
        ps.setLong(1, idMembresia);
        try (ResultSet rs = ps.executeQuery()) {
            while (rs.next()) {
                Object[] datos = new Object[6];
                datos[0] = rs.getLong("ID_pago");
                datos[1] = rs.getDate("Fecha_pago");
                datos[2] = rs.getLong("NumTarjeta");
                datos[3] = rs.getString("Banco");
                datos[4] = rs.getInt("Cvv");
                datos[5] = rs.getString("MembresiaInfo");
                modelo.addRow(datos);
            }
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al cargar pagos: " + e.toString());
    }
}
    
     
private void limpiarCampos() {
    txtTarjeta.setText("");
    txtCvv.setText("");
    cmbBanco.setSelectedIndex(-1);
}

private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {
    String texto = txtIDMem.getText().trim();
    if (texto.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Ingrese un ID de membresía.");
        return;
    }
    try {
        long id = Long.parseLong(texto);
        idMembresia = id;
        cargarInfoMembresia(id);
        cargarPagos();
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "El ID debe ser un número.");
    }
}
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelArt = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtIDMem = new javax.swing.JTextField();
        txtTarjeta = new javax.swing.JTextField();
        btnMod = new javax.swing.JButton();
        btnAlta = new javax.swing.JButton();
        btnBaja = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblFan = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblFin = new javax.swing.JLabel();
        lblInicio = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblEdo = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtCvv = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cmbBanco = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPago = new javax.swing.JTable();

        jPanelArt.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro Pago", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 18))); // NOI18N
        jPanelArt.setPreferredSize(new java.awt.Dimension(330, 0));

        jLabel2.setText("ID Membresía:");

        jLabel3.setText("Número de Tarjeta:");

        btnMod.setText("Modificación");
        btnMod.addActionListener(this::btnModActionPerformed);

        btnAlta.setText("Alta");
        btnAlta.addActionListener(this::btnAltaActionPerformed);

        btnBaja.setText("Baja");
        btnBaja.addActionListener(this::btnBajaActionPerformed);

        btnBuscar.setText("Buscar");

        jLabel1.setText("Fan:");

        jLabel4.setText("Información de Membresía");

        jLabel5.setText("Tipo:");

        jLabel6.setText("Fecha Inicio:");

        jLabel7.setText("Fecha Fin:");

        lblFan.setText("-");

        lblTipo.setText("-");

        lblFin.setText("-");

        lblInicio.setText("-");

        jLabel12.setText("Estado: ");

        lblEdo.setText("-");

        jLabel14.setText("CVV: ");

        jLabel15.setText("Banco:");

        javax.swing.GroupLayout jPanelArtLayout = new javax.swing.GroupLayout(jPanelArt);
        jPanelArt.setLayout(jPanelArtLayout);
        jPanelArtLayout.setHorizontalGroup(
            jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArtLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelArtLayout.createSequentialGroup()
                        .addComponent(btnAlta, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMod)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator2)
                    .addGroup(jPanelArtLayout.createSequentialGroup()
                        .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelArtLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIDMem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelArtLayout.createSequentialGroup()
                                .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanelArtLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblFan))
                                    .addGroup(jPanelArtLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblInicio)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelArtLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblTipo))
                                    .addGroup(jPanelArtLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblFin))
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelArtLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblEdo))
                            .addGroup(jPanelArtLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelArtLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelArtLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmbBanco, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanelArtLayout.setVerticalGroup(
            jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelArtLayout.createSequentialGroup()
                .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDMem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(5, 5, 5)
                .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelArtLayout.createSequentialGroup()
                        .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblFan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblInicio)))
                    .addGroup(jPanelArtLayout.createSequentialGroup()
                        .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(lblTipo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblFin))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblEdo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCvv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbBanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanelArtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMod)
                    .addComponent(btnAlta)
                    .addComponent(btnBaja))
                .addGap(42, 42, 42))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro Pago", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Verdana", 0, 18))); // NOI18N

        tbPago.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbPago);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelArt, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelArt, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModActionPerformed
          int filaMod = tbPago.getSelectedRow();
    if (filaMod < 0) {
        JOptionPane.showMessageDialog(null, "Seleccione un pago de la tabla.");
        return;
    }
    if (txtTarjeta.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Ingrese el número de tarjeta.");
        return;
    }
    if (cmbBanco.getSelectedIndex() == -1) {
        JOptionPane.showMessageDialog(null, "Seleccione un banco.");
        return;
    }
    if (txtCvv.getText().trim().isEmpty() || txtCvv.getText().trim().length() != 3) {
        JOptionPane.showMessageDialog(null, "Ingrese un CVV de exactamente 3 dígitos.");
        return;
    }
 
    long idPagoMod = Long.parseLong(tbPago.getValueAt(filaMod, 0).toString());
 
    Conexion objetoConexionMod = new Conexion();
    String sqlMod =
        "UPDATE Administrativo.Pago SET NumTarjeta = ?, Banco = ?, Cvv = ? WHERE ID_pago = ?";
 
    try (Connection conn = objetoConexionMod.establecerConexion();
         PreparedStatement ps = conn.prepareStatement(sqlMod)) {
 
        ps.setLong(1, Long.parseLong(txtTarjeta.getText().trim()));
        ps.setString(2, cmbBanco.getSelectedItem().toString());
        ps.setInt(3, Integer.parseInt(txtCvv.getText().trim()));
        ps.setLong(4, idPagoMod);
        ps.executeUpdate();
 
        JOptionPane.showMessageDialog(null, "Pago modificado correctamente.");
        cargarInfoMembresia(idMembresia);
        cargarPagos();
        limpiarCampos();
 
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al modificar pago: " + e.toString());
    }
    }//GEN-LAST:event_btnModActionPerformed

    private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltaActionPerformed
         if (idMembresia == null) {
        JOptionPane.showMessageDialog(null, "Busque una membresía primero.");
        return;
    }
    if (txtTarjeta.getText().trim().isEmpty()) {
        JOptionPane.showMessageDialog(null, "Ingrese el número de tarjeta.");
        return;
    }
    if (txtTarjeta.getText().trim().length() < 16) {
        JOptionPane.showMessageDialog(null, "El número de tarjeta debe tener al menos 16 dígitos.");
        return;
    }
    if (cmbBanco.getSelectedIndex() == -1) {
        JOptionPane.showMessageDialog(null, "Seleccione un banco.");
        return;
    }
    if (txtCvv.getText().trim().isEmpty() || txtCvv.getText().trim().length() != 3) {
        JOptionPane.showMessageDialog(null, "Ingrese un CVV de exactamente 3 dígitos.");
        return;
    }
 
    Conexion objetoConexionAlta = new Conexion();
    String sqlAlta =
        "INSERT INTO Administrativo.Pago (ID_membresia, Fecha_pago, NumTarjeta, Banco, Cvv) " +
        "VALUES (?, CURRENT_DATE, ?, ?, ?)";
 
    try (Connection conn = objetoConexionAlta.establecerConexion();
         PreparedStatement ps = conn.prepareStatement(sqlAlta)) {
 
        ps.setLong(1, idMembresia);
        ps.setLong(2, Long.parseLong(txtTarjeta.getText().trim()));
        ps.setString(3, cmbBanco.getSelectedItem().toString());
        ps.setInt(4, Integer.parseInt(txtCvv.getText().trim()));
        ps.executeUpdate();
 
        JOptionPane.showMessageDialog(null, "Pago registrado correctamente.\nLa membresía ahora está Activa.");
        cargarInfoMembresia(idMembresia);
        cargarPagos();
        limpiarCampos();
 
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al registrar pago: " + e.toString());
    }
    }//GEN-LAST:event_btnAltaActionPerformed

    private void btnBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBajaActionPerformed
       int filaBaja = tbPago.getSelectedRow();
    if (filaBaja < 0) {
        JOptionPane.showMessageDialog(null, "Seleccione un pago de la tabla.");
        return;
    }
 
    long idPagoBaja = Long.parseLong(tbPago.getValueAt(filaBaja, 0).toString());
 
    Conexion objetoConexionBaja = new Conexion();
    try (Connection conn = objetoConexionBaja.establecerConexion()) {
        conn.setAutoCommit(false);
 
        String sqlDelPago = "DELETE FROM Administrativo.Pago WHERE ID_pago = ?";
        try (PreparedStatement ps = conn.prepareStatement(sqlDelPago)) {
            ps.setLong(1, idPagoBaja);
            ps.executeUpdate();
        }
 
        String sqlUpdMem =
            "UPDATE Adquisicion.Membresia SET Estado = 'Pago Pendiente', " +
            "Fecha_inicio = NULL, Fecha_fin = NULL WHERE ID_membresia = ?";
        try (PreparedStatement ps = conn.prepareStatement(sqlUpdMem)) {
            ps.setLong(1, idMembresia);
            ps.executeUpdate();
        }
 
        conn.commit();
        JOptionPane.showMessageDialog(null, "Pago eliminado.\nLa membresía volvió a 'Pago Pendiente'.");
        cargarInfoMembresia(idMembresia);
        cargarPagos();
        limpiarCampos();
 
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error al eliminar pago: " + e.toString());
    }
    }//GEN-LAST:event_btnBajaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Pago().setVisible(true));
    }
    
    private void tbPagoMouseClicked(java.awt.event.MouseEvent evt) {
    int fila = tbPago.getSelectedRow();
    if (fila >= 0) {
        txtTarjeta.setText(tbPago.getValueAt(fila, 2).toString());
        cmbBanco.setSelectedItem(tbPago.getValueAt(fila, 3).toString());
        txtCvv.setText(tbPago.getValueAt(fila, 4).toString());
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlta;
    private javax.swing.JButton btnBaja;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnMod;
    private javax.swing.JComboBox<String> cmbBanco;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelArt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblEdo;
    private javax.swing.JLabel lblFan;
    private javax.swing.JLabel lblFin;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTable tbPago;
    private javax.swing.JTextField txtCvv;
    private javax.swing.JTextField txtIDMem;
    private javax.swing.JTextField txtTarjeta;
    // End of variables declaration//GEN-END:variables
}

